[package]
name = "poney"
version = "0.1.0"
edition = "2021"

[lib]
name = "poney"
crate-type = ["cdylib"]

[dependencies]
hyper = { version = "0.14.23", features = ["full"] }
pyo3 = { version = "0.18.0", features = ["extension-module"] }
tokio = { version = "1.24.2", features = ["full"] }
